-- MySQL Script generated by MySQL Workbench
-- 12/01/23 17:34:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema newartists
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema newartists
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newartists` DEFAULT CHARACTER SET latin1 ;
USE `newartists` ;

-- -----------------------------------------------------
-- Table `newartists`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newartists`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `telefone` VARCHAR(13) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `newartists`.`obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newartists`.`obra` (
  `idObra` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NULL DEFAULT NULL,
  `autor` VARCHAR(200) NULL DEFAULT NULL,
  `preco` FLOAT NULL DEFAULT NULL,
  `descricao` VARCHAR(10000) NULL DEFAULT NULL,
  `classificacao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idObra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `newartists`.`comprar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newartists`.`comprar` (
  `idComprar` INT(11) NOT NULL AUTO_INCREMENT,
  `datadacompra` DATE NULL DEFAULT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  `cod_usuario` INT(11) NULL DEFAULT NULL,
  `cod_obra` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idComprar`),
  INDEX `Fk__PULICAR` (`cod_usuario` ASC),
  INDEX `Fk___PULICAR` (`cod_obra` ASC),
  CONSTRAINT `Fk__PULICAR`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `newartists`.`usuario` (`idUsuario`),
  CONSTRAINT `Fk___PULICAR`
    FOREIGN KEY (`cod_obra`)
    REFERENCES `newartists`.`obra` (`idObra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `newartists`.`publicar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newartists`.`publicar` (
  `idPublicar` INT(11) NOT NULL AUTO_INCREMENT,
  `nomedapublicacao` VARCHAR(45) NULL DEFAULT NULL,
  `datadepublicacao` DATE NULL DEFAULT NULL,
  `cod_usuario` INT(11) NULL DEFAULT NULL,
  `cod_obra` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idPublicar`),
  INDEX `Fk_PULICAR` (`cod_usuario` ASC),
  INDEX `FkPULICAR` (`cod_obra` ASC),
  CONSTRAINT `FkPULICAR`
    FOREIGN KEY (`cod_obra`)
    REFERENCES `newartists`.`obra` (`idObra`),
  CONSTRAINT `Fk_PULICAR`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `newartists`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
